export function getStyles(theme) {
    return {
        page: {
            minHeight: '100vh',
            minWidth: '100vw',
            width: '100vw',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background:
                theme === 'dark'
                    ? 'linear-gradient(120deg, #232526 0%, #414345 100%)'
                    : 'linear-gradient(120deg, #e0eafc 0%, #cfdef3 100%)',
            fontFamily: 'Segoe UI, Arial, sans-serif',
            transition: 'background 0.3s',
        },
        card: {
            background: theme === 'dark' ? '#23272f' : '#fff',
            boxShadow: '0 4px 24px 0 rgba(34, 60, 80, 0.12)',
            borderRadius: 16,
            padding: 24,
            maxWidth: 1000,
            width: '100%',
            margin: '32px 0',
            transition: 'background 0.3s',
        },
        section: {
            marginBottom: 24,
        },
        flexRow: {
            display: 'flex',
            gap: 16,
            flexWrap: 'wrap',
            alignItems: 'center',
            marginBottom: 12,
        },
        input: {
            padding: '8px 12px',
            border: theme === 'dark' ? '1px solid #444' : '1px solid #bfc9d1',
            borderRadius: 8,
            fontSize: 16,
            outline: 'none',
            transition: 'border 0.2s, background 0.3s, color 0.3s',
            background: theme === 'dark' ? '#2c2f36' : '#f7fafd',
            color: theme === 'dark' ? '#fff' : '#222',
        },
        select: {
            padding: '8px 12px',
            border: theme === 'dark' ? '1px solid #444' : '1px solid #bfc9d1',
            borderRadius: 8,
            fontSize: 16,
            background: theme === 'dark' ? '#2c2f36' : '#f7fafd',
            color: theme === 'dark' ? '#fff' : '#222',
            transition: 'background 0.3s, color 0.3s, border 0.2s',
        },
        button: {
            padding: '8px 20px',
            border: 'none',
            borderRadius: 8,
            background: theme === 'dark' ? '#4f8cff' : '#4f8cff',
            color: '#fff',
            fontWeight: 600,
            fontSize: 16,
            cursor: 'pointer',
            boxShadow: '0 2px 8px 0 rgba(34, 60, 80, 0.10)',
            marginRight: 8,
            marginTop: 4,
            marginBottom: 4,
            transition: 'background 0.2s, box-shadow 0.2s',
        },
        buttonDanger: {
            background: '#ff4f4f',
            color: '#fff',
        },
        table: {
            width: '100%',
            borderCollapse: 'collapse',
            marginTop: 16,
            background: theme === 'dark' ? '#23272f' : '#f7fafd',
            borderRadius: 8,
            overflow: 'hidden',
            color: theme === 'dark' ? '#fff' : '#222',
            transition: 'background 0.3s, color 0.3s',
        },
        th: {
            background: theme === 'dark' ? '#2c2f36' : '#eaf1fb',
            padding: 8,
            border: theme === 'dark' ? '1px solid #444' : '1px solid #dbe6f6',
            fontWeight: 600,
            textAlign: 'center',
            color: theme === 'dark' ? '#fff' : '#222',
            transition: 'background 0.3s, color 0.3s, border 0.2s',
        },
        td: {
            padding: 8,
            border: theme === 'dark' ? '1px solid #444' : '1px solid #dbe6f6',
            textAlign: 'center',
            fontSize: 15,
            color: theme === 'dark' ? '#fff' : '#222',
            transition: 'background 0.3s, color 0.3s, border 0.2s',
        },
        segmentBlock: {
            background: theme === 'dark' ? '#23272f' : '#f2f7fb',
            borderRadius: 8,
            padding: 12,
            marginBottom: 8,
            transition: 'background 0.3s',
        },
        themeToggle: {
            position: 'absolute',
            top: 24,
            right: 24,
            zIndex: 10,
            background: theme === 'dark' ? '#2c2f36' : '#eaf1fb',
            color: theme === 'dark' ? '#fff' : '#222',
            border: 'none',
            borderRadius: 8,
            padding: '8px 16px',
            fontSize: 15,
            cursor: 'pointer',
            boxShadow: '0 2px 8px 0 rgba(34, 60, 80, 0.10)',
            transition: 'background 0.3s, color 0.3s',
        },
    };
}

